---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Seerr CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint, i18n & Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Pnpm Setup
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: 'package.json'

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        env:
          CI: true
        run: pnpm install

      - name: Formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: i18n Check
        run: node bin/check-i18n.js

      - name: Build
        run: pnpm build

  build-and-publish:
    needs: [ci]
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/docker-build.yml
    with:
      version: develop
      tags: |
        type=raw,value=develop
        type=sha
    permissions:
      contents: read
      packages: write
    secrets: inherit
